version: "3.9"
services:
  frontend:
    container_name: front_end_reactjs
    restart: unless-stopped
    build:
      context: ./Dockdir
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app:delegated
      - /app/node_modules
    ports:
      - 8080:3000
    environment:
      - CHOKIDAR_USEPOLLING=true 
    networks:
      - my_net

  backend:
    container_name: back_end_nest
    restart: unless-stopped
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app:delegated
      - /app/node_modules
      - ./backend/nodemon.json:/app/nodemon.json
    ports:
      - 3000:3000
    command: npm start
    environment:
      - CHOKIDAR_USEPOLLING=true 
    networks:
      - my_net

  # postgr:
  #   container_name: postgrade_databse
  #   image: postgres:alpine
  #   ports:
  #     - 5432:5432
  #   restart: unless-stopped

networks:
  my_net:

