version: "3.9"
services:
  frontend:
    container_name: frontend
    restart: unless-stopped
    build:
      context: ./Dockdir
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app:delegated
      - /app/node_modules
    ports:
      - 8080:3000
    environment:
      - CHOKIDAR_USEPOLLING=true 
    networks:
      - my_net

  backend:
    container_name: backend
    restart: unless-stopped
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app:delegated
      - /app/node_modules
      - ./backend/nodemon.json:/app/nodemon.json
    ports:
      - 3000:3000
    command: npm start
    environment:
      - CHOKIDAR_USEPOLLING=true 
    networks:
      - my_net

  # postgres:
  #   image: postgres:latest
  #   container_name: postgres
  #   ports: 
  #       - 5534:5532
  #   restart: always
  #   volumes:
  #       - "./volume_test:/var/lib/postgresql/data"  
  postgres_db:
    container_name: db
    image: postgres:14.1-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PGDATA=${PGDATA}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=${POSTGRES_HOST}
    volumes: 
      # - ./postgres_initdb/schema.sql:/docker-entrypoint-initdb.d/schema.sql:Z
      - ./postgres_data/:/var/lib/postgresql/data

    ports:
      - '5432:5432'
    env_file:
      - .env
    networks:
      - my_net

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: unless-stopped
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - 8081:80
    networks:
      - my_net

networks:
  my_net:

