version: "3.9"
services:
  frontend:
    container_name: front_end_reactjs
    restart: unless-stopped
    build:
      context: frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/frontend:delegated
      - /frontend/node_modules
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true 
    networks:
      - my_net

networks:
  my_net:

